spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          github:
            clientId: ${GH_CLIENT_ID}
            clientSecret: ${GH_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            clientSecret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
jwt:
  secret-key: ${JWT_SECRET_KEY}
cloud:
  aws:
    credentials:
      access-key: AKIA36PBVZQMY62YYREP
      secret-key: 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
