spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create