spring:
  datasource:
    url: jdbc:mysql://pathfinder.cb7wjtx0ljjo.ap-northeast-2.rds.amazonaws.com:3306/mydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: park0522
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath*:db/mysql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update