spring:
  profiles: local

  datasource:
    url: jdbc:mysql://pathfinder.cb7wjtx0ljjo.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver