spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          github:
            clientId: ${GIT_CLIENT_ID}
            clientSecret: ${GIT_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          kakao:
            clientId: ${K_CLIENT_ID}
            clientSecret: ${K_CLIENT_SECRET}
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
jwt:
  secret-key: ${JWT_SECRET_KEY}