spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 830692934800-9ulik9a4p22hd38uulbpghsrvabn17ab.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          github:
            clientId: 7dca96040ea08f34a56a
            clientSecret: a6330dd162444fcbf246121236437bb63a1f7c58
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app
          kakao:
            clientId: a79191966acfe756c8d2e2ecc0d52c3c
            clientSecret: 46a02c85547acc937e7b0e76995db4af
            redirect-uri: https://port-0-seb45-main-020-54ouz2lllpv0a22.sel3.cloudtype.app

jwt:
  secret-key: "fasdfasasdflkne2721KHjApxlkaeQwqiofdsalkfnHqwouie234231412fkdsjafbeuwqpfbWdsadflfbasEfklwuiqefblskf34214asdLkljfbsaldraDsDdrkljfb316792mqeifjwola248nawCepqmbvoZihwWYeq19d2e549135abTMan6mongDzmcvq"